// <auto-generated />
namespace EstacionamientoDF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RemoveColumnParkingLotAdmin_IdFromTableParkingLot : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemoveColumnParkingLotAdmin_IdFromTableParkingLot));
        
        string IMigrationMetadata.Id
        {
            get { return "201608061837594_RemoveColumnParkingLotAdmin_IdFromTableParkingLot"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
